name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Firebase Test Lab Action
      uses: asadmansr/Firebase-Test-Lab-Action@v1.0
      with:
      # a YAML formatted file that includes arguments for gcloud firebase test run command.
        arg-spec: tests.yml
      env:
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
