name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      
      - name: Unit Tests
        run: ./gradlew test
        
#   androidTest:
#     runs-on: macos-latest
#     strategy:
#       matrix:
#         api-level: [21, 23, 29]
#         target: [default, google_apis]
#     steps:
#     - name: checkout
#       uses: actions/checkout@v2

#     - name: run tests
#       uses: reactivecircus/android-emulator-runner@v2
#       with:
#         api-level: ${{ matrix.api-level }}
#         target: ${{ matrix.target }}
#         arch: x86_64
#         profile: Nexus 6
#         script: ./gradlew connectedCheck
